spring.application.name=runnershigh

mybatis.mapper-locations=mappers/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.datasource.url=jdbc:mysql://localhost:3306/runnershigh
spring.datasource.username=root
spring.datasource.password=Root1234!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

